// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TakeHome.API.Models;

#nullable disable

namespace TakeHome.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260308150434_InitialBaseline")]
    partial class InitialBaseline
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TakeHome.API.Models.Item", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemId"));

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("ModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("ItemId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("TakeHome.API.Models.Packaging", b =>
                {
                    b.Property<int>("PackagingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PackagingId"));

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("ModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("PackagingTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("ParentPackagingId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("PackagingId");

                    b.HasIndex("PackagingTypeId");

                    b.HasIndex(new[] { "ParentPackagingId" }, "IX_Packaging_ParentId");

                    b.HasIndex(new[] { "ProductId" }, "IX_Packaging_ProductId");

                    b.ToTable("Packaging", (string)null);
                });

            modelBuilder.Entity("TakeHome.API.Models.PackagingItem", b =>
                {
                    b.Property<int>("PackagingItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PackagingItemId"));

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("PackagingId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("PackagingItemId");

                    b.HasIndex(new[] { "ItemId" }, "IX_PackagingItems_ItemId");

                    b.HasIndex(new[] { "PackagingId" }, "IX_PackagingItems_PackagingId");

                    b.ToTable("PackagingItems");
                });

            modelBuilder.Entity("TakeHome.API.Models.PackagingType", b =>
                {
                    b.Property<int>("PackagingTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PackagingTypeId"));

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("ModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("PackagingTypeId");

                    b.ToTable("PackagingTypes");
                });

            modelBuilder.Entity("TakeHome.API.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("ModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Sku")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("SKU");

                    b.HasKey("ProductId");

                    b.HasIndex(new[] { "Sku" }, "UQ__Products__CA1ECF0D0088C12D")
                        .IsUnique()
                        .HasFilter("[SKU] IS NOT NULL");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("TakeHome.API.Models.Packaging", b =>
                {
                    b.HasOne("TakeHome.API.Models.PackagingType", "PackagingType")
                        .WithMany("Packagings")
                        .HasForeignKey("PackagingTypeId")
                        .IsRequired()
                        .HasConstraintName("FK_Packaging_Type");

                    b.HasOne("TakeHome.API.Models.Packaging", "ParentPackaging")
                        .WithMany("InverseParentPackaging")
                        .HasForeignKey("ParentPackagingId")
                        .HasConstraintName("FK_Packaging_Parent");

                    b.HasOne("TakeHome.API.Models.Product", "Product")
                        .WithMany("Packagings")
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("FK_Packaging_Product");

                    b.Navigation("PackagingType");

                    b.Navigation("ParentPackaging");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("TakeHome.API.Models.PackagingItem", b =>
                {
                    b.HasOne("TakeHome.API.Models.Item", "Item")
                        .WithMany("PackagingItems")
                        .HasForeignKey("ItemId")
                        .IsRequired()
                        .HasConstraintName("FK_PackagingItems_Item");

                    b.HasOne("TakeHome.API.Models.Packaging", "Packaging")
                        .WithMany("PackagingItems")
                        .HasForeignKey("PackagingId")
                        .IsRequired()
                        .HasConstraintName("FK_PackagingItems_Packaging");

                    b.Navigation("Item");

                    b.Navigation("Packaging");
                });

            modelBuilder.Entity("TakeHome.API.Models.Item", b =>
                {
                    b.Navigation("PackagingItems");
                });

            modelBuilder.Entity("TakeHome.API.Models.Packaging", b =>
                {
                    b.Navigation("InverseParentPackaging");

                    b.Navigation("PackagingItems");
                });

            modelBuilder.Entity("TakeHome.API.Models.PackagingType", b =>
                {
                    b.Navigation("Packagings");
                });

            modelBuilder.Entity("TakeHome.API.Models.Product", b =>
                {
                    b.Navigation("Packagings");
                });
#pragma warning restore 612, 618
        }
    }
}
